name: Validate changelog
description: "Validation changelog based on changelog-schema.json"
author: Kong

inputs:
  files:
    description: 'The changelog files'
    required: true

runs:
  using: composite
  steps:
    - uses:  actions/checkout@v4
      with:
        repository: Kong/gateway-changelog
        path: gateway-changelog

    - name: validates changelogs
      uses: thiagodnf/yaml-schema-checker@58b96413951ebe86a396275c48620b8435439694 # v0.0.10
      with:
        jsonSchemaFile: gateway-changelog/changelog-schema.json
        yamlFiles: ${{ inputs.files }}
